# For more information, see: http://docs.haskellstack.org/en/stable/yaml_configuration/

resolver: lts-9.12

packages:
- '.'
extra-deps: []

flags: {}

extra-package-dbs: []

system-ghc: false

ghc-build: nopie
ghc-options:
    "$locals": -fwarn-unused-imports
