#!/usr/bin/env zsh

set -eu

# 0 0,4,8,12,16,20 * * * sleep $(( $RANDOM \% 60 + 60 )); $HOME/bin/jobs/update-blog &> /var/tmp/blaglog.cron

build-site() {
    # `cabal exec` doesn't work on NixOS for some reason
    # cabal exec site clean
    # cabal exec site build

    dist/build/site/site clean
    dist/build/site/site build

    rsync --delete -a _site/ 'blog:$HOME/html/'
}

cd $HOME/code/haskell/blag

# Run the potentially very expensive `cabal build` manually, please:
# nix-shell -E "$(cabal2nix --shell .)" --run 'cabal build'

build-site 2>&1 | tee /var/tmp/blaglog
