#!/bin/sh

dir="reports"
where="$dir/report$1"

mkdir -p "$dir"

if tty -s; then
    ./get
    cat access.log
else
    cat
fi | \
     \
./filter | tee "$dir/clean" | ./stats | sort | uniq -c | sort -nr > ${where}_
(grep /posts/ < ${where}_; echo; cat ${where}_ | grep -v /posts/) > $where
rm ${where}_
ls -l "$dir/clean" $where
