#!/bin/sh

mkdir -p logs
name="logs/$(date +%F)-access.log"

if ! getent hosts blog > /dev/null; then
    cp sample-logs $name
else
    scp 'blog:$HOME/logs/access.log' $name
fi

ln -sf $name access.log
