#!/bin/sh

mkdir -p logs
name="logs/$(date +%Y-%m)-access.log"

if ! getent hosts blog > /dev/null && ! grep -rEl '^ *Host blog *$' ~/.ssh > /dev/null; then
    cp sample-logs "$name"
else
    cp "logs/$(ls logs | tail -n1)" "$name"
    rsync -v 'blog:$HOME/logs/access.log' "$name"
fi

ln -sf "$name" access.log
